'''Kautsar Muhammad Mizan
RPL 1C
2404073'''
print ("Mobil Lama Pak Oki adalah: ")
print ("Merk: Honda")
print ("Tipe: HRV")
print ("Warna: Hitam")
print ("Tahun: 2018")
print ()
print ("Masukkan informasi detail mobil baru")
Merk = (input("Merk: "))
Tipe = (input("Tipe Mobil: "))
Tahun = (input("Tahun keluaran: "))
Warna = (input("Warna: "))
No = (input("No. Polisi: "))
Bensin = (input("Bensin: "))
Transmisi = (input("Transmisi: "))
print ()
print ("-------------***-------------")
print ("Mobil baru Pak Oki adalah:")
print ("Merk: ", Merk )
print ("Tipe: ", Tipe)
print ("Warna: ", Warna)
print ("Tahun: ", Tahun)
print ("-------------***-------------")